version: '3'

services:

  fs-parity:
    image: b32147/docker-snapraid
    environment:
      PUID: 1001
    network_mode: bridge
    volumes:
      - ./fs-parity:/config
      - /mnt/data0:/mnt/data0
      - /mnt/data1:/mnt/data1
      - /mnt/parity0:/mnt/parity0
    restart: always

  fs-pool:
    build:
      context: ./fs-pool
      args:
        UID: 1001
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    network_mode: none
    volumes:
      - media:/mnt/pool
      - /mnt/data0:/mnt/data0
      - /mnt/data1:/mnt/data1
    restart: always

  media-server:
    image: linuxserver/plex
    environment:
      PUID: 1001
      TZ: GB
      VERSION: latest
    network_mode: host
    volumes:
      - media:/data:ro
      - media-config:/config
      - /tmp/transcode:/transcode
    depends_on:
      - fs-parity
      - fs-pool
    restart: always

  player:
    image: nicjo814/docker-plexmediaplayer
    privileged: true
    environment:
      GFX_DRIVER: radeon
    volumes:
      - /tmp:/tmp
    links:
      - media-server
    restart: always

  samba:
    image: dperson/samba
    command: |
      -s 'media;/mount/media;yes;no;yes'
      -s 'media-config;/mount/media-config;yes;yes;yes'
    environment:
      NMBD:
      TZ: GB
      USERID: 1001
      WORKGROUP: WORKGROUP
    ports:
      - 139:139
      - 445:445
    volumes:
      - media:/mount/media
      - media-config:/mount/media-config:ro
    depends_on:
      - fs-parity
      - fs-pool
    restart: always

volumes:
  media:
  media-config:
