version: '3'

services:

  fs-parity:
    image: carlba/snapraid
    network_mode: bridge
    volumes:
      - ./snapraid:/config
      - /mnt/data0:/mnt/data0
      - /mnt/data1:/mnt/data1
      - /mnt/data2:/mnt/data2
      - /mnt/data3:/mnt/data3
      - /mnt/parity0:/mnt/parity0
    restart: always

  fs-pool:
    image: darrin0101/mergerfs
    network_mode: none
    volumes:
      - media:/mnt/data
      - /mnt/data0:/mnt/data0
      - /mnt/data1:/mnt/data1
      - /mnt/data2:/mnt/data2
      - /mnt/data3:/mnt/data3
    restart: always

  media-server:
    image: linuxserver/plex
    environment:
      TZ: GB
      VERSION: latest
    network_mode: host
    volumes:
      - media:/data:ro
      - media-config:/config
      - /tmp/transcode:/transcode
    depends_on:
      - fs-parity
      - fs-pool
    restart: always

  player:
    image: nicjo814/docker-plexmediaplayer
    privileged: true
    links:
      - media-server
    restart: always

  samba:
    image: dperson/samba
    ports:
      - 139:139
      - 445:445
    volumes:
      - media:/mount/media
      - media-config:/mount/media-config:ro
    depends_on:
      - fs-parity
      - fs-pool
    restart: always

volumes:
  media:
  media-config:
