version: '2.3'

services:

  analytics:
    image: linuxserver/plexpy
    environment:
      PUID: 1001
      TZ: GB
    ports:
      - 8181:8181
    volumes:
      - ./app-config/tautulli:/config
      - ./app-config/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    restart: always

  fs-parity:
    image: b32147/docker-snapraid
    entrypoint: /entrypoint.sh
    environment:
      PUID: 1001
    network_mode: bridge
    # Uncomment to run `snapraid smart`
    # The alternative is `cap_add: - SYS_ADMIN` and listing all disk devices...
    # ...better not to list them manually, and be privileged iff we need to be.
    #privileged: true
    volumes:
      - ./fs-parity/entrypoint.sh:/entrypoint.sh
      - ./fs-parity/snapraid-runner.conf:/config/snapraid-runner.conf
      - ./fs-parity/var:/var/snapraid
      - ./disks/media:/mnt/data:rslave
      - ./disks/parity:/mnt/parity
    restart: always

  fs-pool:
    build:
      context: ./fs-pool
      args:
        DISK_MOUNTS_DIR: /mnt
        POOL_MOUNTPOINT: /pool
        UID: 1001
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    network_mode: none
    volumes:
      - ./disks/media:/mnt
      - ./media:/pool:rshared
    restart: always
    healthcheck:
      test: test $$(find $$POOL_MOUNTPOINT -name '*.mkv' | wc -l) -ne 0
      interval: 10s
      timeout: 2s
      retries: 60
      start_period: 10s

  media-server:
    image: linuxserver/plex
    environment:
      PUID: 1001
      TZ: GB
      VERSION: latest
    network_mode: host
    volumes:
      - ./media:/data:ro
      - ./app-config/plex:/config
      - /dev/shm:/transcode
    depends_on:
      fs-parity:
        condition: service_started
      fs-pool:
        condition: service_healthy
    restart: always

  samba:
    image: dperson/samba
    command: |
      -s 'media;/mount/media;yes;no;yes'
      -s 'media-config;/mount/media-config;yes;yes;yes'
    environment:
      NMBD:
      TZ: GB
      USERID: 1001
      WORKGROUP: WORKGROUP
    ports:
      - 139:139
      - 445:445
    volumes:
      - ./media:/mount/media:rslave
      - ./app-config:/mount/media-config:ro
    depends_on:
      - fs-parity
      - fs-pool
    restart: always
