version: '3'

services:

  fs-parity:
    image: b32147/docker-snapraid
    environment:
      PUID: 1001
    network_mode: bridge
    volumes:
      - ./fs-parity:/config
      - ./disks/media:/mnt/media
      - ./disks/parity:/mnt/parity
    restart: always

  fs-pool:
    build:
      context: ./fs-pool
      args:
        DISK_MOUNTS_DIR: /mnt
        POOL_MOUNTPOINT: /pool
        UID: 1001
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    network_mode: none
    volumes:
      - ./disks/media:/mnt
      - ./media:/pool:rshared
    restart: always

  media-server:
    image: linuxserver/plex
    environment:
      PUID: 1001
      TZ: GB
      VERSION: latest
    network_mode: host
    volumes:
      - ./media:/data:ro
      - media-config:/config
      - /dev/shm:/transcode
    depends_on:
      - fs-parity
      - fs-pool
    restart: always

  player:
    image: nicjo814/docker-plexmediaplayer
    privileged: true
    environment:
      GFX_DRIVER: radeon
    volumes:
      - /tmp:/tmp
    links:
      - media-server
    restart: always

  samba:
    image: dperson/samba
    command: |
      -s 'media;/mount/media;yes;no;yes'
      -s 'media-config;/mount/media-config;yes;yes;yes'
    environment:
      NMBD:
      TZ: GB
      USERID: 1001
      WORKGROUP: WORKGROUP
    ports:
      - 139:139
      - 445:445
    volumes:
      - ./media:/mount/media:rslave
      - media-config:/mount/media-config:ro
    depends_on:
      - fs-parity
      - fs-pool
    restart: always

volumes:
  media-config:
